// Run after installing web-next dependencies; no runtime web dependency on iOS.
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const ios = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const check = args.includes('--check');
const modules = args.find(value => !value.startsWith('--')) ?? path.join(ios, '..', 'web-next', 'node_modules');
const require = createRequire(path.join(modules, '_symbols.cjs'));
const React = require('react');
const { renderToStaticMarkup } = require('react-dom/server');
const icons = require('lucide-react');
const mapping = JSON.parse(fs.readFileSync(path.join(ios, 'Design/Symbols.json'), 'utf8'));
const app = path.join(ios, 'Agents Anywhere/Agents Anywhere');
// Xcode strips a trailing 'Image' from asset symbols, which would collide with File.
const assetName = name => name === 'FileImage' ? 'aa-ImageFile' : 'aa-' + name;
function output(filename, content) {
  if (check) {
    if (!fs.existsSync(filename) || fs.readFileSync(filename, 'utf8') !== content) {
      throw new Error(`Outdated Lucide resource: ${path.relative(ios, filename)}`);
    }
  } else {
    fs.mkdirSync(path.dirname(filename), { recursive: true });
    fs.writeFileSync(filename, content);
  }
}
for (const name of new Set(Object.values(mapping))) {
  if (!icons[name]) throw new Error(`Missing Lucide icon: ${name}`);
  const directory = path.join(app, 'Assets.xcassets', `${assetName(name)}.imageset`);
  const svg = renderToStaticMarkup(React.createElement(icons[name], { color: '#000000', size: 24, strokeWidth: 2 }))
    .replace(/ class="[^"]*"| aria-hidden="[^"]*"/g, '');
  output(path.join(directory, `${name}.svg`), svg + '\n');
  output(path.join(directory, 'Contents.json'), JSON.stringify({
    images: [{ filename: `${name}.svg`, idiom: 'universal' }],
    info: { author: 'xcode', version: 1 },
    properties: { 'preserves-vector-representation': true, 'template-rendering-intent': 'template' },
  }, null, 2) + '\n');
}
const entries = Object.entries(mapping).map(([symbol, name]) => `        ${JSON.stringify(symbol)}: ${JSON.stringify(assetName(name))},`).join('\n');
output(path.join(app, 'Views/Components/AppSymbolAssets.swift'),
  '// Generated by ios/scripts/sync-symbols.mjs from the Web Lucide icons.\nimport Foundation\n\nenum AppSymbolAssets {\n    static let names: [String: String] = [\n' + entries + '\n    ]\n}\n');
const version = require('lucide-react/package.json').version;
output(path.join(app, 'Resources/Notices/Lucide.txt'), `Lucide ${version}\nhttps://lucide.dev\n\n` + fs.readFileSync(path.join(modules, 'lucide-react/LICENSE'), 'utf8'));
console.log(`${check ? 'Verified' : 'Updated'} ${new Set(Object.values(mapping)).size} vector icons from Lucide ${version}.`);
