"""Tests for the host-service JSON mappers.

The platform-id vectors below were generated by the plugin-era TypeScript
`platformSessionId` (the implementation lived at
`opencode-plugin/src/shared/protocol.ts` before that package was retired; its
reports are preserved under `docs/opencode-plugin-evidence/`), so this file is
the cross-language guard: if the Python derivation drifts by one character,
every session Agents Anywhere already lists turns into a new one.
"""

from __future__ import annotations

import pytest

from connector.runtimes.opencode.serve.mappers import (
    agent_catalog,
    model_catalog,
    platform_session_id,
    session_meta,
)

# (namespace, external id, expected platform id) -- from the TypeScript side.
PLATFORM_ID_VECTORS = [
    ("conn_abc123", "ses_f22107110ffdwOAm3Bcv9JiTBV", "sess_opencode_483ab98929c931747183f076"),
    ("aa:device-1", "ses_01", "sess_opencode_9f1bf76078cf24a33f2db356"),
    ("x", "ses_", "sess_opencode_8ff94645c1abcd06853e341b"),
]


@pytest.mark.parametrize(("namespace", "external", "expected"), PLATFORM_ID_VECTORS)
def test_platform_id_matches_the_plugin_derivation_byte_for_byte(
    namespace: str, external: str, expected: str
) -> None:
    assert platform_session_id(namespace, external) == expected


def test_session_meta_carries_the_host_id_and_the_parent_link() -> None:
    row = {
        "id": "ses_child",
        "projectID": "prj_1",
        "parentID": "ses_parent",
        "title": "P4 账号+spawn+打包",
        "agent": "team",
        "model": {"id": "glm-5.3", "providerID": "lxns-uni"},
        "location": {"directory": "D:\\Github\\Agents-Anywhere"},
        "time": {"created": 1, "updated": 1790481286387},
        "cost": 0.63,
        "tokens": {"input": 10},
    }
    meta = session_meta(row, namespace="ns")
    assert meta.external_session_id == "ses_child"
    assert meta.session_id == platform_session_id("ns", "ses_child")
    assert meta.runtime == "opencode"
    assert meta.title == "P4 账号+spawn+打包"
    assert meta.cwd == "D:\\Github\\Agents-Anywhere"
    assert meta.ordering_time == "1790481286387"
    assert meta.metadata["parentID"] == "ses_parent"
    assert meta.metadata["agent"] == "team"


def test_session_meta_rejects_rows_without_an_id() -> None:
    with pytest.raises(ValueError):
        session_meta({"title": "nameless"}, namespace="ns")


def test_model_catalog_keys_by_provider_so_repeated_ids_survive() -> None:
    # Measured shape of the real defect: the same bare id from two providers.
    rows = [
        {"id": "longcat-2.5-preview-free", "providerID": "lxns-uni", "name": "LongCat 2.5", "enabled": True},
        {"id": "longcat-2.5-preview-free", "providerID": "backup-gw", "name": "LongCat backup"},
        {"id": "glm-5.3", "providerID": "lxns-uni", "name": "GLM 5.3", "capabilities": {"reasoning": True}},
    ]
    catalog = model_catalog(rows, revision=4)
    assert catalog.revision == 4
    assert [item.id for item in catalog.models] == [
        "lxns-uni/longcat-2.5-preview-free",
        "backup-gw/longcat-2.5-preview-free",
        "lxns-uni/glm-5.3",
    ]
    ids = [item.id for item in catalog.models]
    selections = [item.selection_id for item in catalog.models]
    assert len(set(ids)) == len(ids), "the server rejects a catalog over a duplicate id"
    assert len(set(selections)) == len(selections), "…or a duplicate selection id"
    first = catalog.models[0]
    assert first.title == "LongCat 2.5"
    # The write path rebuilds `Model.Ref` from these, not from the composite key.
    assert first.metadata["id"] == "longcat-2.5-preview-free"
    assert first.metadata["providerID"] == "lxns-uni"


def test_model_catalog_skips_rows_it_cannot_address() -> None:
    rows = [{"id": "no-provider"}, {"providerID": "no-model"}, "not-an-object"]
    assert model_catalog(rows).models == ()


def test_agent_catalog_keeps_modes_and_falls_back_to_all() -> None:
    rows = [
        {"id": "build", "mode": "primary"},
        {"id": "general", "mode": "subagent", "hidden": True},
        {"id": "weird", "mode": "made-up"},
        {"name": "no-id"},
    ]
    catalog = agent_catalog(rows)
    assert [(item.id, item.mode, item.hidden) for item in catalog.agents] == [
        ("build", "primary", False),
        ("general", "subagent", True),
        ("weird", "all", False),
    ]
    assert catalog.runtime == "opencode"
